# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('rollno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(default='Male', max_length=6)),
                ('marks', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='credentials',
            unique_together=set([('rollno', 'name', 'marks')]),
        ),
    ]
