# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcealloc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='res_num',
            new_name='resource',
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together=set([('username', 'resource', 'request_date')]),
        ),
    ]
