# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='DOB')),
                ('rollno', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('rollno', 'fname')]),
        ),
    ]
