# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='person',
            name='rollno',
        ),
    ]
